apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# ../../kustomize/api-service/base
#- ../../kustomize/application-crds
#- ../../kustomize/argo
#- ../../kustomize/centraldashboard
#- ../../kustomize/cert-manager
#- ../../kustomize/cert-manager-crds
#- ../../kustomize/cert-manager-kube-system-resources
#- ../../kustomize/dex
- ./jupyter-web-app
- ../../kustomize/application
- ../../kustomize/application-crds
- ../../kustomize/istio
- ../../kustomize/istio-crds
- ../../kustomize/istio-install
