apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace:
spec:
  rules:
  - host: dev-kustomize-guestbook-argocd-check-deploy.natwest-labs.com
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
        path: /
