apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: 184774810209.dkr.ecr.ap-southeast-1.amazonaws.com/test:latest
    kaniko:
      dockerfile: Dockerfile
      buildContext:
        localDir: {}
      cache: {}
  cluster:
    namespace: argo
    pullSecretName: 
    dockerConfig:
      secretName: docker-cfg-secret