apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/krithiva/argocd-example-apps:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/krithiva/argocd-example-apps:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: argocd-example-apps
        chartPath: charts/argocd-example-apps
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/krithiva/argocd-example-apps"
          image.tag: "{{.DIGEST_HEX}}"
