apiVersion: batch/v1
kind: Job
metadata:
  name: sync-2
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-weight: 2
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sh", "-c", "echo 2 && sleep 10"]
      restartPolicy: Never
  backoffLimit: 0
