apiVersion: batch/v1
kind: Job
metadata:
  name: dms-migrations
spec:
  template:
    spec:
      containers:
      - name: dms-migrations
        image: curlimages/curl
        command:
          - "curl"
          - "-k"
          - "-X"
          - "GET"
          - "www.google.com"
      restartPolicy: Never
  backoffLimit: 4
