apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kustomize-guestbook-ingress
  namespace:
spec:
  rules:
  - host: kustomize-guestbook-argocd1.natwest-labs.com
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
        path: /
