apiVersion: v1
data:
  index2.html: |
    <html>
      <heaad></head>
      <body>
        <p>Testing configMaps auto reloading</p>
      </body>
    </html>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: kustomize-guestbook
  name: guestbook-cm
  namespace: default
