apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-delete-me
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: jsonnet-guestbook
    repoURL: https://github.com/a-mankinenko/test-apps-argo.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: gitops-rt
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
