apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: volvo-kustomize/application-crds
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}



