apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app
  namespace: kubeflow
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: jupyter-web-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
