apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-200
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:dgadavin/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: test-200
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
