apiVersion: v1
kind: Service
metadata:
  name: wordpress-app
spec:
  ports:
  - nodePort: 30256
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-app
  type: LoadBalancer
