apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: docker.artifactory.a.intuit.com/dev/deploy/kayenta/service/kayenta.deserialize
        name: guestbook-ui
        ports:
        - containerPort: 80
