apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - nodePort: 30256
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
  type: LoadBalancer
