apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-service-replica-1
  name: echo-service-replica-1
  namespace: sleepme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service-replica-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-service-replica-1
    spec:
      containers:
      - image: davidebianchi/echo-service
        name: echo-service
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: do-not-sleep
  name: do-not-sleep
  namespace: sleepme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-not-sleep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: do-not-sleep
    spec:
      containers:
      - image: davidebianchi/echo-service
        name: echo-service
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-service-replica-4
  name: echo-service-replica-4
  namespace: sleepme
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-service-replica-4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-service-replica-4
    spec:
      containers:
      - image: davidebianchi/echo-service
        name: echo-service
        resources: {}
status: {}
